hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  gen_batch_size: ${data.train_batch_size}
  custom_cls:
    path: "pkg://recipe.recap.recap_dataset"
    name: "RECAPDataset"
  instruction_key: instruction
  prefill_key: prefill_prompts

reward:
  custom_reward_function:
    path: "pkg://recipe.recap.recap_reward"
    name: "compute_score"
  reward_manager:
    name: dapo
  reward_kwargs:
    overlong_buffer_cfg:
      enable: False
      len: 0
      penalty_factor: 0.0
      log: False
    max_resp_len: ${data.max_response_length}

actor_rollout_ref:
  rollout:
    agent:
      default_agent_loop: recap_agent
      agent_loop_config_path: "recipe/recap/config/recap_agent_loops.yaml"

algorithm:
  filter_groups:
    _target_: verl.trainer.config.FilterGroupsConfig
    enable: False
    metric: null
    max_num_gen_batches: 0

trainer:
  project_name: verl-recap
